# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84459acb050ac1a398692d6ba92ffbc366797acc42976bd1a250174d1340bb9527f0ee067f22dd33c7328ccb0d33cc72d1a755ca99cbcbc6718361ac5a5ded01

test:
  secret_key_base: 73dd969ce85673e48c30133dc7526d0fa303a8d1162be5de8e9bc3685d2323ab07ee9d5ec387909210c1596b01b92398ddcd5dbdd52305f0523e7748d8b473c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
